language: r
r:
  - release
  - devel
  
r_check_args: --as-cran

osx_image: xcode12u
  
cache: packages

os:
  - osx
  - linux

env:
  global:
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE
    
addons:
  homebrew:
    packages: 
    - ffmpeg
    - imagemagick@6
    
sudo: required
dist: xenial
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ibmagick++-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libfftw3-dev ; fi
  
 

# removed, went  to addons instead -> before_install: - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install imagemagick@6; fi

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
  