language: r
r:
  - release
osx_image: xcode12u
  
cache: packages

os:
  - osx

addons:
  homebrew:
    packages: ffmpeg, imagemagick@6

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
  