language: r
r:
  - oldrel
  - release
  - bioc-devel
  
cache: packages
os:
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi


addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - gsfonts