# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
bioc_packages: EBImages
os:
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi