language: r
r:
  - oldrel
  - release
  
cache: packages
os:
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install imagemagick@6; fi