language: r
r:
  - release
osx_image: xcode12.2
  
cache: packages
os:
  - osx


before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install imagemagick@6; fi

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
  