# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
  
cache: packages

os:
  - osx
  
install: 
  - R -e 'install.packages("BiocManager"); BiocManager::install("EBImage")'
  - R -e 'install.packages("data.table", "dplyr", "Momocs", "raster", "zoo", "plyr", "pastecs", "animation", "features", "wesanderson", "ggplot2","testhat")' #install these because of devel issues "Package suggested but not available: ‘testthat’" 
  
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi