language: r
r:
  - oldrel
  - release
  - bioc-devel
  
cache: packages
bioc_packages: EBImage
os:
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi