# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap
  
  # Prepend desired Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - pip install --upgrade pip --user
  - pip install pipenv

  # Find latest image magick version by parsing website

  - python find_latest_imagemagick_version.py > temp.txt
  - set /p IMAGE_MAGICK_VERSION=<temp.txt

  - echo %IMAGE_MAGICK_VERSION%
  # Download ImageMagick installer (which also installs ffmpeg.)
  # From http://ftp.fifi.org/ImageMagick/binaries/
  # Might need to be updated from time to time
  # Versions >=7.0 have problems - executables changed names.
  # Assume 64-bit. Need to change to x86 for 32-bit.
  - curl https://imagemagick.org/download/binaries/ImageMagick-%IMAGE_MAGICK_VERSION%-%ARCH%-static.exe -o ImageMagick.exe

  # Install ImageMagick, telling InnoSetup to not open a window and change default install dir
  - ImageMagick.exe /SILENT /SP /DIR="%IMAGE_MAGICK_INSTALL_DIR%"

  # Inspect contents and set env vars
  - dir "%IMAGE_MAGICK_INSTALL_DIR%"
  - set IMAGEMAGICK_BINARY=%IMAGE_MAGICK_INSTALL_DIR%//convert.exe
  - echo %IMAGEMAGICK_BINARY%
  - set FMPEG_BINARY="%IMAGE_MAGICK_INSTALL_DIR%//ffmpeg.exe"
  - echo %FMPEG_BINARY%


cache:
  - C:\RLibrary

environment:
  NOT_CRAN: true
  # env vars that may need to be set, at least temporarily, from time to time
  # see https://github.com/krlmlr/r-appveyor#readme for details
  # USE_RTOOLS: true
  # R_REMOTES_STANDALONE: true
  global:
    IMAGE_MAGICK_INSTALL_DIR: c://ImageMagick

# Adapt as necessary starting from here
#https://gist.github.com/kevinGodell/fa3e33c5fcade59ab57c5a7232fb28dc
#https://gist.github.com/kevinGodell/fa3e33c5fcade59ab57c5a7232fb28dc #For ffmpeg
build_script:
  - travis-tool.sh install_bioc EBImage #order matters, build depends on this first
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps
 
test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
