---
output:
  github_document:
    html_preview: true
---

# Notes for build
    - see (this)[https://github.com/r-lib/pkgdown/issues/1157] for SSL error workaround
    -`httr::set_config(httr::config(ssl_verifypeer = 0L)); 
pkgdown::build_site(pkg = ".", new_process = FALSE)`

# Notes for testing/CI

  * follow these pointers for `pkgdown` site build with CI on Travis
  * check travis.yaml with https://config.travis-ci.com/explore
  * imagemagick requirements related to ubuntu/linux https://srvanderplas.netlify.app/post/2019-05-07-travis-tricks/
  * **Jul '21** migrate away from Travis to GH actions: https://deanattali.com/blog/migrating-travis-to-github/ 
  * for GH actions :  `usethis::use_github_action_check_standard()` 
  * then copy badges
  * delete `- {os: windows-latest, r: 'release'}` from yaml file under '.github\workflows' 
  * this last step assumes appveyor is running the Windows build with `ffmpeg` install
  * added `- {os: macOS-latest, r: 'devel'}` for macOS devel build
  * see also: https://www.rostrum.blog/2020/08/09/ghactions-pkgs/
  * for code coverage with gh action: `usethis::use_github_action("test-coverage")`
  * Used tic for initial yml: https://docs.ropensci.org/tic/articles/tic.html#initialization-setup
  * For biocon dependencies: https://github.com/r-lib/actions/actions/runs/100691291/workflow
  * Now editing 'workflow.yml' directly.
  * Error with R Devel on Linux and Mac: see https://github.com/r-hub/rhub/issues/471
  
  
  
    
# Notes for gitting/site

  * `usethis::use_pkgdown()` for `pkgdown`
  * `pkgdown::build_articles` and `pkgdown::build_site`
  * see: https://www.datacamp.com/community/tutorials/cd-package-docs-pkgdown-travis
  * see: https://cran.r-project.org/web/packages/pkgdown/vignettes/pkgdown.html
  * abandoned deploy, now going with static, but often builds of site locally with push to git [a la](https://sahirbhatnagar.com/blog/2020/03/03/creating-a-website-for-your-r-package/)
    - `pkgdown::build_site()` for build
    - `use_travis_deploy()` broken with:
    
```
Error: `github_token()` was deprecated in usethis 2.0.0 and is now defunct.
Call `gh::gh_token()` to retrieve a GitHub personal access token
Call `gh_token_help()` if you need help getting or configuring your token
```
  
# Versioning

  * Follow: https://yihui.org/en/2013/06/r-package-versioning/




 